name: my fisrt workflow
on:
  push:
   branches: main
jobs:
   fisrt_job:
      runs-on: ubuntu-latest
      steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Set up Docker
         uses: docker/setup-buildx-action@v2
       - name: Build and Run Docker Compose
         run: |
          docker compose -f docker-compose.yml config
          docker compose -f docker-compose.yml up -d --build
          docker compose -f docker-compose.yml ps